name: labram_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nodefaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy
  - matplotlib  # Don't pin 3.10.0 yet – it doesn’t exist as of June 2025
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - sympy=1.13.1
  - mne=1.9.0
  - pytorch=2.6.0
  - torchvision=0.21.0
  - pip
  - pip:
      - torcheeg==1.1.3
      - timm==1.0.15
      - wandb
